Fix require resolve error on windows 10
After a bare install following instructions, hit this : Error: Cannot find module 'C:\code\testmodels/..configconfig.json'